      # 步驟二：編譯
      - name: Install and Build
        run: |
          npm install
          npm run build
          yarn install
          yarn build
        env:
          VUE_APP_API: ${{ secrets.VUE_APP_API }}
      # 步驟三：部署
