      # 步驟二：編譯
      - name: Install and Start
        run: |
          npm install
          npm start
          yarn install
          yarn start
        env:
          VUE_APP_API: ${{ secrets.VUE_APP_API }}
      # 步驟三：部署
